services:
  # DATABASE
  db:
    image: mysql:8.0 # Или mariadb:10.6
    container_name: wisswan-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wisswan           # Имя базы
      MYSQL_ROOT_PASSWORD: root         # Пароль рута
      MYSQL_USER: admin                 # Твой пользователь
      MYSQL_PASSWORD: admin             # Пароль пользователя
    volumes:
      - db_data:/var/lib/mysql         # ДАННЫЕ НЕ ПРОПАДУТ МЕЖДУ БИЛДАМИ
      # МАГИЯ ДЛЯ ДАМПА:
      - ./init-db:/docker-entrypoint-initdb.d # Сюда положи свой дамп
    networks:
      - wisswan-network

  # --- СЕРВИС БЭКЕНДА (Laravel) ---
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend      # Где искать Dockerfile для этого сервиса
      dockerfile: Dockerfile  # Имя файла (если оно стандартное, можно не писать)
    container_name: wisswan-backend
    restart: unless-stopped   # Перезапускать контейнер, если он упал (но не если вы сами его выключили)
    
    # применяю миграции к базе
    command: >
      sh -c "until php artisan db:monitor; do
               echo 'Waiting for database connection...';
               sleep 2;
             done;
             php artisan migrate;
             php-fpm"
    depends_on:
      - db
    networks:
      - wisswan-network       # Подключаем к общей сети, чтобы видеть фронтенд и базу

  # Воркер для обработки задач в фоне
  queue:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wisswan-queue
    restart: unless-stopped
    # Используем ту же логику ожидания базы, что и в бэкенде
    # --tries=2 Если задача упапа, то попробует ещё раз её выполнить
    # --timeout=20 Если задача выполняется более 20-ти секунд, то ложить её
    command: >
      sh -c "until php artisan db:monitor; do
               echo 'Waiting for DB in queue...';
               sleep 2;
             done;
             php artisan queue:work --verbose --tries=2 --timeout=20"
    volumes:
      - ./backend:/var/www
      - /var/www/vendor  # Не дает локальной папке перекрыть папку в контейнере
    depends_on:
      - db
      - backend
    networks:
      - wisswan-network


   # Node.js service (use with: docker compose up wisswan-frontend --build)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wisswan-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000" # Пробрасываем порт: [порт на компе]:[порт в контейнере]
    depends_on:
      - backend               # Фронт не запустится, пока не поднимется бэкенд
    networks:
      - wisswan-network


  # --- СЕРВИС ВЕБ-СЕРВЕРА (Nginx) ---
  nginx:
    image: nginx:alpine       # Берем готовый легкий образ Nginx
    container_name: wisswan-nginx
    restart: unless-stopped
    ports:
      - "80:80"               
      - "443:443"             
    volumes:
      # Пробрасываем конфиг, который мы написали ранее
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Пробрасываем папку бэкенда, чтобы Nginx видел папку public (для картинок и статики)
      - ./backend:/var/www
      # SSL сертификаты
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - backend
      - frontend
    networks:
      - wisswan-network
      

# --- ОБЪЯВЛЕНИЕ ТОМОВ И СЕТЕЙ (строго в начале строки) ---
volumes:
  db_data: # Объявляем том в конце файла


# Описание сети, в которой будут общаться наши контейнеры
networks:
  wisswan-network:
    driver: bridge # Стандартный драйвер для связи на одном хосте
