services:
  nginx:
    build:
      context: ./backend
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    volumes:
      # Mount the 'laravel-storage' volume to '/var/www/storage' inside the container.
      # -----------------------------------------------------------
      # This volume stores persistent data like uploaded files and cache.
      # The ':ro' option mounts it as read-only in the 'nginx' service because Nginx only needs to read these files.
      # The 'php-fpm' service mounts the same volume without ':ro' to allow write operations.
      # -----------------------------------------------------------
      - laravel-storage-production:/var/www/storage:ro
      # SSL сертификаты. 
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - wisswan-production
    ports:
      # Map port 80 inside the container to the port specified by 'NGINX_PORT' on the host machine.
      # -----------------------------------------------------------
      # This allows external access to the Nginx web server running inside the container.
      # For example, if 'NGINX_PORT' is set to '8080', accessing 'http://localhost:8080' will reach the application.
      # -----------------------------------------------------------
      - "${NGINX_PORT:-80}:80"
      - "443:443"             
    depends_on:
      php-fpm:
        condition: service_healthy # Wait for php-fpm health check
      frontend:
        condition: service_started # Wait for php-fpm health check

  # Laravel: route handler
  php-fpm:
    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
    build:
      context: ./backend
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production # Use the 'production' stage in the Dockerfile
    restart: unless-stopped
    volumes:
      - laravel-storage-production:/var/www/storage # Mount the storage volume
    env_file:
      - ./backend/.env
    networks: 
      - wisswan-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    # The 'depends_on' attribute with 'condition: service_healthy' ensures that
    # this service will not start until the 'postgres' service passes its health check.
    # This prevents the application from trying to connect to the database before it's ready.
    depends_on:
      postgres:
        condition: service_healthy

  # The Laravel 'php-cli' service provides a command-line interface for running Artisan commands and other CLI tasks.
  # -----------------------------------------------------------
  # This is useful for running migrations, seeders, or any custom scripts.
  # It shares the same codebase and environment as the 'php-fpm' service.
  # -----------------------------------------------------------
  php-cli:
    build:
      context: ./backend
      dockerfile: ./docker/production/php-cli/Dockerfile
    tty: true # Enables an interactive terminal
    stdin_open: true # Keeps standard input open for 'docker exec'
    env_file:
      - ./backend/.env
    networks:
      - wisswan-production

  laravel-queue:
    build:
      context: ./backend
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    # --tries=2 Если задача упапа, то попробует ещё раз её выполнить
    # --timeout=20 Если задача выполняется более 20-ти секунд, то ложить её
    # Переопределяем дефолтную команду php-fpm на запуск воркера Laravel
    command: php artisan queue:work --verbose --tries=2 --timeout=20
    env_file:
      - ./backend/.env
    volumes:
      - laravel-storage-production:/var/www/storage
    networks:
      - wisswan-production
    depends_on:
      postgres:
        condition: service_healthy

  laravel-schedule:
    build:
      context: ./backend
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    tty: true
    restart: always
    # Переопределяем дефолтную команду php-fpm на запуск воркера Laravel
    command: php artisan schedule:work
    env_file:
      - ./backend/.env
    volumes:
      - laravel-storage-production:/var/www/storage
    networks:
      - wisswan-production
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/production/Dockerfile
    container_name: wisswan-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: "3000"
    env_file:
      - ./frontend/.env  
    ports:
      - "3000:3000" # Пробрасываем порт: [порт на компе]:[порт в контейнере]
    depends_on:
      - php-fpm               # Фронт не запустится, пока не поднимется бэкенд
    networks:
      - wisswan-production
    
  postgres:
    image: postgres:18
    restart: unless-stopped
    user: postgres
    ports:
      - "5433:5432" # [порт на компе]:[порт в контейнере]
    environment:
      - POSTGRES_DB=wisswan
      - POSTGRES_USER=wisswan
      - POSTGRES_PASSWORD=rQVz2rMRPNVU
    volumes:
      - postgres-data-production:/var/lib/postgresql
    networks:
      - wisswan-production
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wisswan"]
      interval: 10s
      timeout: 5s
      retries: 5

  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped # Automatically restart unless the service is explicitly stopped
  #   networks:
  #     - laravel-production
  #   # Health check for Redis
  #   # -----------------------------------------------------------
  #   # Checks if Redis is responding to the 'PING' command.
  #   # This ensures that the service is not only running but also operational.
  #   # -----------------------------------------------------------
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

networks:
  wisswan-production:

volumes:
  laravel-storage-production:
  postgres-data-production:
