services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    user: postgres
    ports:
      - "5433:5432" # [порт на компе]:[порт в контейнере]
    environment:
      - POSTGRES_DB=wisswan
      - POSTGRES_USER=wisswan
      - POSTGRES_PASSWORD=rQVz2rMRPNVU
    volumes:
      - postgres-data-development:/var/lib/postgresql
    networks:
      - wisswan-development

  nginx:
    image: nginx:latest
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    networks:
      - wisswan-development
    ports:
      - "80:80" # [порт на компе]:[порт в контейнере]
    volumes:
      # Mount the application code for live updates
      - ./backend:/var/www
      - ./backend/docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      php-fpm:
        condition: service_started # Wait for php-fpm health check
      frontend:
        condition: service_started # Wait for php-fpm health check

  # Laravel: route handler
  php-fpm:
    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
    build:
      context: ./backend
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    restart: unless-stopped
    env_file:
      - ./backend/.env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      # Mount the application code for live updates
      - ./backend:/var/www
    networks:
      - wisswan-development
    depends_on:
      postgres:
        condition: service_started

  workspace:
   # For the workspace service, we will also create a custom image to install and setup all the necessary stuff.
    build:
      context: ./backend
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    tty: true  # Enables an interactive terminal
    stdin_open: true  # Keeps standard input open for 'docker exec'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www
    networks:
      - wisswan-development


  laravel-queue:
    build:
      context: ./backend
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
    restart: unless-stopped
    # --tries=2 Если задача упапа, то попробует ещё раз её выполнить
    # --timeout=20 Если задача выполняется более 20-ти секунд, то ложить её
    # Переопределяем дефолтную команду php-fpm на запуск воркера Laravel
    command: php artisan queue:work --verbose --tries=2 --timeout=20
    env_file:
      - ./backend/.env
    volumes:
      # Mount the application code for live updates
      - ./backend:/var/www
    networks:
      - wisswan-development
    depends_on:
      postgres:
        condition: service_started

  # раскоментить при необходимости
  # laravel-schedule:
  #   build:
  #     context: ./backend
  #     dockerfile: ./docker/common/php-fpm/Dockerfile
  #     target: development
  #   tty: true
  #   restart: always
  #   # Переопределяем дефолтную команду php-fpm на запуск воркера Laravel
  #   command: php artisan schedule:work
  #   env_file:
  #     - ./backend/.env
  #   volumes:
  #     # Mount the application code for live updates
  #     - ./backend:/var/www
  #   networks:
  #     - wisswan-development
  #   depends_on:
  #     postgres:
  #       condition: service_started


  frontend:
    build:
      context: ./frontend
      dockerfile: docker/development/Dockerfile
    container_name: wisswan-frontend
    environment:
      PORT: "3000"
    volumes:
      - ./frontend:/app   # Весь ваш локальный код прокидывается внутрь контейнера в реальном времени
      # - /app/node_modules # защищает node_modules в контейнере
    ports:
      - "3000:3000"           # [порт на компе]:[порт в контейнере]
    depends_on:
      - php-fpm               # Фронт не запустится, пока не поднимется бэкенд
    networks:
      - wisswan-development
  

  # redis:
  # image: redis:alpine
  # networks:
  #   - wisswan-development

networks:
  wisswan-development:

volumes:
  postgres-data-development:

