[www]
;user = www-data
;group = www-data

;pm = dynamic
;pm.max_children = 10 ; максимум 10 одновременных запросов к PHP
;pm.start_servers = 1 ; сколько воркеров держать запущенными всегда
;pm.min_spare_servers = 1 ; минимальный запас свободных воркеров
;pm.max_spare_servers = 3 ; максимальный запас свободных воркеров
;pm.max_requests = 500 ; Перезапуск воркеров. Убить процесс и запустить чистый новый после 500 запросов

pm.status_path = /status ; ОБЯЗАТЕЛЬНО ДЛЯ СКАЧАННОГО ХЕЛСЧЕКА: