# Используем официальный образ PHP с менеджером процессов FPM
FROM php:8.3-fpm

# Устанавливаем системные утилиты + libicu-dev для расширения intl
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libicu-dev \
    zip \
    unzip

# Устанавливаем расширения PHP
RUN docker-php-ext-configure intl \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd intl

# Копируем Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY composer.json composer.lock ./
RUN composer install --no-scripts --no-autoloader

COPY . .

RUN php artisan storage:link 

RUN sh -c composer dump-autoload && \
    chown -R www-data:www-data storage bootstrap/cache && \
    php artisan storage:link
