name: Next CI
on:  # когда воркфлоу триггерить
  push: 
    # Запускать только если изменились файлы во фронтенде
    paths:
      - 'frontend/**'
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest # на чём запускать
    defaults:
      run:
        # по умолчанию выполняются внутри папки frontend
        working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install dependencies
        run: npm install
      - name: eslint
        run: npx eslint .
  tests:
    needs: [ eslint ]       # без линта не запускать
    strategy:               # что-то вроде переменых. по факту множества
      matrix:
        version: [24]
    runs-on: ubuntu-latest  # на чём запускать
    
    defaults:
      run:
        # по умолчанию выполняются внутри папки frontend
        working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}
      - name: install dependencies
        run: npm install
      - name: test
        run: npm run test

